version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    open-pull-requests-limit: 30

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
