version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    open-pull-requests-limit: 30
    groups:
      cargo-metadata:
        patterns:
          - "cargo_metadata"
          - "clap-cargo"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
